name: "Deploy Frontend to Azure Static Web Apps"

on:
  workflow_dispatch:
    inputs:
      deployment_token:
        description: "Azure Static Web App API Token"
        required: true
        type: string
      function_name:
        description: "Azure Function Name (e.g., 'func-satellite-test' without the URL)"
        required: true
        type: string
      vm_ip:
        description: "Backend VM IP Address (e.g., '192.168.1.50')"
        required: true
        type: string

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ inputs.deployment_token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: ""
          output_location: "dist"

        env:
          VITE_INGESTION_API: "https://${{ inputs.function_name
            }}.azurewebsites.net/api/QueryCopernicusAPI"
          VITE_PROCESSOR_API: "https://${{ inputs.vm_ip }}:8000/process"
          VITE_WS_API: "wss://${{ inputs.vm_ip }}:8000/ws"
