name: "Deploy Function to Azure"

on:
  workflow_dispatch:
    inputs:
      function_app_name:
        description: "Name of the Azure Function App (e.g., 'func-satellite-test')"
        required: true
        type: string
      postgres_connection_string:
        description: "PostgreSQL Connection String"
        required: true
        type: string

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "backend/SatelliteIngestion"
  PYTHON_VERSION: "3.11"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Resolve Project Dependencies
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Function App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ inputs.function_app_name }}
          app-settings-json: |
            [
              {
                "name": "CDSE_CLIENT_ID",
                "value": "${{ secrets.CDSE_CLIENT_ID }}",
                "slotSetting": false
              },
              {
                "name": "CDSE_CLIENT_SECRET",
                "value": "${{ secrets.CDSE_CLIENT_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "POSTGRES_CONNECTION_STRING",
                "value": "${{ inputs.postgres_connection_string }}",
                "slotSetting": false
              }
            ]

      - name: Deploy Azure Function App
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.function_app_name }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
